name: Deploy to Production

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    concurrency:
      group: production_environment
      cancel-in-progress: true
    runs-on: ubuntu-latest
    # environment:
    #   name: production
    #   url: https://example.com
    timeout-minutes: 20

    env:
      DOCKER_BUILDKIT: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: ./.github/actions/setup
        name: Setup
        with:
          ssh-private-key: ${{ secrets.KAMAL_SSH_PRIVATE_KEY }}

      - name: Release Lock
        run: |
          kamal lock release

      - name: Registry Login
        run: |
          kamal registry login --skip-remote

      - name: Build
        run: |
          kamal build push

      - name: Deploy
        run: |
          kamal deploy --skip-push
