name: Deploy Manually

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      destination:
        description: "Select a destination"
        required: true
        default: "production"
        type: choice
        options:
          - production

jobs:
  deploy-production:
    name: Deploy to production
    if: ${{ github.event.inputs.destination == 'production' }}
    concurrency:
      group: production_environment
      cancel-in-progress: true
    runs-on: ubuntu-latest
    # environment:
    #   name: production
    #   url: https://example.com
    timeout-minutes: 20

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: ./.github/actions/setup
        name: Setup
        with:
          ssh-private-key: ${{ secrets.KAMAL_SSH_PRIVATE_KEY }}
